name: Build and Deploy Sringboot app

on: 
  push:
    branches:
      - main

jobs:
  build-Deploy:
    name: Build and Deploy Spring boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the on
        run:
          mvn clean
          mvn -B package --file pom.xml

      

