name: Build and Deploy Sringboot app

on: 
  push:
    branches:
      - main

jobs:
  build-Deploy:
    name: Build and Deploy Spring boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run: mvn clean & mvn -B package --file pom.xml
      
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: docker.io/${{secrets.dockeruser}}/spring-boot-for-beginners-github-actions:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.dockeruser}}
          password: ${{secrets.dockerpwd}}

      - name: Push to docker
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: docker.io/${{secrets.dockeruser}}/spring-boot-for-beginners-github-actions:latest


      

